### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by gvsurenderreddy** [fangdingjun/wstunnel#1]
I'm unable to understand the client and server configure cannot please help how can i use it this wonderful software

**Comment by fangdingjun** [comment]
example

on server side,  listen for websocket connection and forward it to ssh port, example config


    proxy_config:
        - listen: ws://127.0.0.1:2222/p1
          remote: tcp://127.0.0.1:22

on client side, forward the connection through websocket, example config

    proxy_config:
        -  listen: tcp://127.0.0.1:9001
           remote: ws://127.0.0.1:2222/p1

now, you connect to ssh server  use  `ssh -p 9001 127.0.0.1`, your ssh connection hide in websocket

the websocket can be proxied by nginx also

**Comment by gvsurenderreddy** [comment]
prefect solution thanks i"ll try
